### ISSUE TITLE
How to pass a parametar to gulp_inject ?

### ISSUE THREAD

**Issue by zmarkoni** [DerekSeverson/gulp-inject-stringified-html#1]
Here is the example function:

function sayHello() {
  return { gulp_inject: './hello.html' };  // <-- and this! 
}

---

Basically I have tried this and it won't work, I was wondering why?

var data = './hello.html';
function sayHello(data) {
  return { gulp_inject: data };  // Wont work with parameter!
}

**Comment by DerekSeverson** [comment]
@zmarkoni, sorry for the late response.

The `{ gulp_inject: './hello.html' }` syntax may be a bit misleading.  What the gulp_inject_stringified_html does is scan through your code using regex to find something that looks like `{ gulp_inject: '<your_file_path>' }` and then just replaces the whole matching expression to the stringified html found at `<your_file_path>`.  It does not run your code or know anything about variables.  The only reason why I chose the `{ gulp_inject: '<your_file_path>'}` is so developer's IDE and Linters wouldn't complain about bad JS syntax when doing auto completion.  

Let me know if you have any other questions.
