### ISSUE TITLE
Catch Error

### ISSUE THREAD

**Issue by mikestreety** [DerekSeverson/gulp-inject-stringified-html#2]
Hello!

Firstly, thank you so much for the plugin - it's perfect and exactly what I was after.

I have come across a slight issue though - if I try and include a HTML file that doesn't exist yet (e.g. if I'm including it before I create it) the plugin fails and breaks my `gulp-watch`.

Normally in this instance, i'm able to catch the error in a gulp `.on('error', function(){});` - however this doesn't seem to be the case with this plugin?

Unfortunately, I don't know enough about node & such to do a PR!

**Comment by DerekSeverson** [comment]
Hi @mikestreety - 
Glad this plugin was what you were looking for! 
**Let me know if version 1.0.4 fixed your issue.**  
Thanks!
